
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.applet.*;
import java.awt.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MyJFrame.java
 *
 * Created on 2009-6-25, 9:09:52
 */

/**
 *
 * @author Administrator
 */
public class MyJFrame extends javax.swing.JFrame {

    /** Creates new form MyJFrame */
    public MyJFrame() {
        initComponents();
    	
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void initComponents() {
    	this.setTitle("SaleSystem");
    	this.setBackground(Color.green);
        jScrollPane1 = new javax.swing.JScrollPane();
        Font font = new Font("宋体", Font.PLAIN, 20);//创建1个字体实例
        
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameJTF = new javax.swing.JTextField();
        queryJB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idJTF_D = new javax.swing.JTextField();
        ageJTF_D = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameJTF_D = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addressJTF_D = new javax.swing.JTextField();
        addJB = new javax.swing.JButton();
        deleteJB = new javax.swing.JButton();
        jLabel1.setFont(font);//设置JLabel的字体
        //jLabel1.setForeground(Color.PINK);//设置文字的颜色
        queryJB.setFont(font);
        nameJTF.setFont(font);
        jLabel2.setFont(font);
        idJTF_D.setFont(font);
        ageJTF_D.setFont(font);
        jLabel3 .setFont(font);
        jLabel4.setFont(font);
        nameJTF_D.setFont(font);
        jLabel5.setFont(font);
        addressJTF_D.setFont(font);
        addJB.setFont(font);
        deleteJB.setFont(font);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "name", "number", "price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.setBackground(Color.CYAN);
        jScrollPane1.setVisible(true);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("查询"));

        jLabel1.setText("name");

        queryJB.setText("查询");
        queryJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryJBActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            //jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                //.addComponent(nameJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, javax.swing.GroupLayout.DEFAULT_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 193, Short.MAX_VALUE)
                .addComponent(queryJB))
        );
        jPanel1Layout.setVerticalGroup(
            //jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           // .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        		.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                //.addComponent(nameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nameJTF, javax.swing.GroupLayout.PREFERRED_SIZE,30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(queryJB))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("显示"));

        jLabel2.setText("ID");

        jLabel3.setText("number");

        jLabel4.setText("name");

        jLabel5.setText("price");

        addJB.setText("增加");
        addJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJBActionPerformed(evt);
            }
        });

        deleteJB.setText("删除");
        deleteJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            //jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                //.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        //.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    		.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ageJTF_D)
                            .addComponent(idJTF_D, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameJTF_D, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressJTF_D, javax.swing.GroupLayout.PREFERRED_SIZE,300, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(deleteJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addJB))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idJTF_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(nameJTF_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageJTF_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(addressJTF_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJB)
                    .addComponent(deleteJB))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        //jScrollPane1.paint(all);

       pack();
    }// </editor-fold>//GEN-END:initComponents

    private void queryJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryJBActionPerformed
        // TODO add your handling code here:
        String url="jdbc:odbc:driver={Microsoft Access Driver (*.mdb)};DBQ=d:\\aaa.mdb";
        Connection conn = null;
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn = DriverManager.getConnection(url , "" , "");    //字段和表名应为英文
            Statement statement=conn.createStatement();
            ResultSet rs=statement.executeQuery("select * from test where name='"+this.nameJTF.getText()+"'");
            DefaultTableModel dtm=(DefaultTableModel)this.jTable1.getModel();
            for(int i=0;i<dtm.getRowCount();i++) dtm.removeRow(i);
            while(rs.next())
            {
                String data[]=new String[4];
                data[0]=rs.getString("id");
                data[1]=rs.getString("name");
                data[2]=rs.getString("age");
                data[3]=rs.getString("address");
                dtm.addRow(data);
            }
            conn.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

            
        

}//GEN-LAST:event_queryJBActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel)this.jTable1.getModel();
        int curRow=this.jTable1.getSelectedRow();
        if(curRow>=0)
        {
            String id=(String)dtm.getValueAt(curRow,0);
            String name=(String)dtm.getValueAt(curRow,1);
            String age=(String)dtm.getValueAt(curRow,2);
            String address=(String)dtm.getValueAt(curRow,3);
            this.idJTF_D.setText(id);
            this.nameJTF_D.setText(name);
            this.ageJTF_D.setText(age);
            this.addressJTF_D.setText(address);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void addJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJBActionPerformed
        // TODO add your handling code here:
        String url="jdbc:odbc:driver={Microsoft Access Driver (*.mdb)};DBQ=d:\\aaa.mdb";
        Connection conn = null;
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn = DriverManager.getConnection(url , "" , "");    //字段和表名应为英文
            Statement statement=conn.createStatement();
            String name=this.nameJTF_D.getText();
            String age=this.ageJTF_D.getText();
            String address=this.addressJTF_D.getText();
            String sqlStr="insert into test (name,age,address) values('"+name+"',"+age+",'"+address+"')";
            statement.executeUpdate(sqlStr);
            
            DefaultTableModel dtm=(DefaultTableModel)this.jTable1.getModel();
            for(int i=0;i<dtm.getRowCount();i++) dtm.removeRow(i);
            ResultSet rs=statement.executeQuery("select * from test");
            while(rs.next())
            {
                String data[]=new String[4];
                data[0]=rs.getString("id");
                data[1]=rs.getString("name");
                data[2]=rs.getString("age");
                data[3]=rs.getString("address");
                dtm.addRow(data);
            }
            conn.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_addJBActionPerformed

    private void deleteJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJBActionPerformed
        // TODO add your handling code here:
        String url="jdbc:odbc:driver={Microsoft Access Driver (*.mdb)};DBQ=d:\\aaa.mdb";
        Connection conn = null;
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn = DriverManager.getConnection(url , "" , "");    //字段和表名应为英文
            Statement statement=conn.createStatement();
            String id=this.idJTF_D.getText();
            String sqlStr="delete from test where id="+id;
            statement.executeUpdate(sqlStr);
            this.idJTF_D.setText("");
            this.nameJTF_D.setText("");
            this.ageJTF_D.setText("");
            this.addressJTF_D.setText("");            
            DefaultTableModel dtm=(DefaultTableModel)this.jTable1.getModel();
            for(int i=0;i<dtm.getRowCount();i++) dtm.removeRow(i);
            ResultSet rs=statement.executeQuery("select * from test");
            while(rs.next())
            {
                String data[]=new String[4];
                data[0]=rs.getString("id");
                data[1]=rs.getString("name");
                data[2]=rs.getString("age");
                data[3]=rs.getString("address");
                dtm.addRow(data);
            }
            conn.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteJBActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJB;
    private javax.swing.JTextField addressJTF_D;
    private javax.swing.JTextField ageJTF_D;
    private javax.swing.JButton deleteJB;
    private javax.swing.JTextField idJTF_D;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameJTF;
    private javax.swing.JTextField nameJTF_D;
    private javax.swing.JButton queryJB;
    // End of variables declaration//GEN-END:variables

}
